version: '3.7'
services:

  rabbitmq:
    restart: always
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=80%
      - C_FORCE_ROOT=true
    hostname: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /opt/data/rabbitmq:/var/lib/rabbitmq

  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /opt/data/post/:/var/lib/postgresql/data/
    ports:
      - '5432:5432'



  app:
    build:
      context: .
      target: DJANGO_APP
    volumes:
      - /opt/data/staticfiles:/app/staticfiles
      - .:/app
    ports:
      - '8000:8000'
    command: gunicorn --env DJANGO_SETTINGS_MODULE=GD.settings.production GD.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - db


  celery:
    build: .
    command : celery -A GD worker -l INFO
    volumes:
      - .:/app
    env_file: .env

    depends_on:
<<<<<<< HEAD
      - rabbitmq
=======
      - rabbitmq

>>>>>>> origin/master
