# Generated by Django 3.1.4 on 2021-01-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210120_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='presentation_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='presentation_link',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('descriptions', models.TextField()),
                ('linked_in', models.URLField(blank=True)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='EventService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_state', models.CharField(choices=[('CM', 'COMPLETED'), ('PN', 'PENDING'), ('RJ', 'REJECTED')], default='PN', max_length=2)),
                ('service', models.CharField(choices=[('WS', 'WORKSHOP'), ('TK', 'TALK')], max_length=2)),
                ('Workshop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.workshop')),
                ('talk', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.talk')),
            ],
        ),
        migrations.AddField(
            model_name='talk',
            name='presenters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.presenter'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='presenters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.presenter'),
        ),
    ]
