# Generated by Django 3.1.4 on 2021-01-23 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20210120_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='presenters',
            new_name='presenter',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='presenters',
            new_name='presenter',
        ),
        migrations.RemoveField(
            model_name='eventservice',
            name='Workshop',
        ),
        migrations.AddField(
            model_name='eventservice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventservice',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.workshop'),
        ),
        migrations.AddField(
            model_name='talk',
            name='level',
            field=models.CharField(choices=[('BG', 'BEGINNER'), ('IM', 'INTERMEDIATE'), ('EX', 'EXPERT')], default='BG', max_length=2),
        ),
        migrations.AddField(
            model_name='workshop',
            name='level',
            field=models.CharField(choices=[('BG', 'BEGINNER'), ('IM', 'INTERMEDIATE'), ('EX', 'EXPERT')], default='BG', max_length=2),
        ),
        migrations.AlterField(
            model_name='eventservice',
            name='service',
            field=models.CharField(choices=[('WS', 'WORKSHOP'), ('TK', 'TALK'), ('CP', 'COMPETITION')], max_length=2),
        ),
        migrations.AlterField(
            model_name='eventservice',
            name='talk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.talk'),
        ),
        migrations.AddField(
            model_name='eventservice',
            name='competion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.competition'),
        ),
    ]
