# Generated by Django 3.1.4 on 2021-01-20 08:02

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phone_number',
            field=models.CharField(max_length=32, validators=[user.models.PhoneValidator()], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='user_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='user name'),
        ),
    ]
