# Generated by Django 3.1.4 on 2021-01-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210120_0816'),
        ('user', '0002_auto_20210120_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='talks',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='workshops',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.eventservice'),
        ),
    ]
