# Generated by Django 3.1.4 on 2021-01-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210120_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='services',
        ),
    ]
