name: Django CI

on:
  push:
    branches: [ "master", "tests" ]
  pull_request:
    branches: [ "master", "test" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install libpq-dev python3.11-dev
          sudo apt install rabbitmq-server
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          mv .env.example .env
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test
